import { HEX_SYMBOL_COUNT, HEX_SYMBOL_SCROLL_COUNT } from './hex';

// SIZES
export const CONTAINER_HEIGHT = 100;
export const CHARACTER_HEIGHT = 40;
export const SPACING_HEIGHT = 30;
const FULL_ITEM_HEIGHT = CHARACTER_HEIGHT + SPACING_HEIGHT;
const MIDPOINT = CONTAINER_HEIGHT / 2 - CHARACTER_HEIGHT / 2;

export const BASE_DURATION = 3;
const BASE_ARRAY_REPEATS = 4;
const BASE_SCROLL_ARRAY_REPEATS = 1;
export const ITEMS_PER_SECOND =
  (HEX_SYMBOL_COUNT * BASE_ARRAY_REPEATS) / BASE_DURATION;
export const END_DELAY_MULTIPLIER = 0.66;

export const START = -(
  FULL_ITEM_HEIGHT * BASE_ARRAY_REPEATS * HEX_SYMBOL_COUNT -
  MIDPOINT -
  FULL_ITEM_HEIGHT
);
export const END = MIDPOINT;
export const SCROLL_START = -(
  FULL_ITEM_HEIGHT * BASE_SCROLL_ARRAY_REPEATS * HEX_SYMBOL_SCROLL_COUNT -
  MIDPOINT -
  FULL_ITEM_HEIGHT
);
